spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/tsodgis"
    username: "postgres"
    password: "postgres"
  jpa:
    generate-ddl: "true"
assm:
  app:
    jwtSecret: "jwtAssmSecretKey"
    jwtExpiration: "86400"